export const siteConfig = {
  name: 'WayOfProcessing',
  title: 'WayOfProcessing — Stripe Payment Processing',
  titleRu:
    'Купить Stripe аккаунт | Верифицированный готовый аккаунт — WayOfProcessing',
  titleEn:
    'Buy Verified Stripe Account | Stripe Account for Sale — WayOfProcessing',
  description:
    'Stripe payment processing for any niche from 1.5%. Warmed-up accounts, 99.9% uptime, CRM access and unlimited withdrawals in EUR, USD and USDT.',
  descriptionRu:
    'Купить Stripe аккаунт или арендовать готовый верифицированный аккаунт с оборотом. Продажа Stripe аккаунтов для бизнеса. Процессинг от 1.5%, вывод EUR/USD/USDT.',
  descriptionEn:
    'Buy verified Stripe account with instant delivery. Stripe account for sale — warmed, ready for business. Rent or buy. Processing from 1.5%. Payouts in EUR, USD, USDT.',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://wayofprocessing.com',
  email: 'hello@wayofprocessing.com',
  telegram: '@wayofprocessing',
  telegramChannelUrl: 'https://t.me/wayofprocessing',
  telegramOperatorUrl: 'https://t.me/wayofprocessing',
  locale: 'ru_RU',
  alternateLocale: 'en_US',
  ogImage: '/images/hero-stripe.png',
  ogImageAlt: 'WayOfProcessing — международный процессинг платежей через Stripe',
  themeColor: '#635BFF',
  keywordsRu: [
    'купить stripe аккаунт',
    'купить верифицированный stripe',
    'купить аккаунт stripe готовый',
    'готовый stripe аккаунт',
    'stripe аккаунт на продажу',
    'продажа stripe аккаунтов',
    'купить stripe аккаунт бизнес',
    'аренда stripe аккаунта',
    'арендовать аккаунт stripe',
    'stripe аккаунт купить дешево',
    'stripe аккаунт цена',
    'приобрести аккаунт stripe',
    'stripe аккаунт с документами',
    'магазин stripe аккаунтов',
    'процессинг stripe',
    'WayOfProcessing',
  ],
  keywordsEn: [
    'buy verified stripe account',
    'stripe account for sale',
    'buy stripe account instant delivery',
    'buy stripe account',
    'rent stripe account',
    'buy aged stripe account',
    'ready stripe account',
    'stripe merchant account',
    'stripe payment processing',
    'WayOfProcessing',
  ],
  keywords: [
    'купить stripe аккаунт',
    'купить верифицированный stripe',
    'готовый stripe аккаунт',
    'аренда stripe аккаунта',
    'buy verified stripe account',
    'stripe account for sale',
    'buy stripe account instant delivery',
    'WayOfProcessing',
  ],
  seo: {
    slogan: 'Международный процессинг Stripe от 1.5%',
    disclaimer:
      'WayOfProcessing — независимый сервис и не является аффилированным лицом, партнёром или дочерней компанией Stripe, Inc.',
    disclaimerEn:
      'WayOfProcessing is an independent service and is not affiliated with, endorsed by, or a subsidiary of Stripe, Inc.',
    contentLanguages: 'ru, en',
    knowsAbout: [
      'Buy Stripe account',
      'Rent Stripe account',
      'Verified Stripe accounts',
      'Stripe account for sale',
      'Stripe payment processing',
      'Stripe account setup',
      'Warmed Stripe accounts',
      'Payment routing',
      'International payment acceptance',
      'High-risk payment processing',
      'Stripe API integration',
      'E-commerce checkout',
      'PCI DSS compliance',
      'Chargeback management',
      'Stripe webhooks',
      'Cross-border payments',
    ],
    stats: {
      accountsCreated: 1100,
      yearsExperience: 7,
      clientVolume: '$53M+',
      uptime: '99.9%',
      commissionFrom: '1.5%',
    },
    areaServed: ['Worldwide', 'European Union', 'United Kingdom', 'United States', 'CIS'],
  },
  pages: {
    blog: {
      title: 'Блог WayOfProcessing — Stripe, процессинг и интеграции',
      titleEn: 'WayOfProcessing Blog — Stripe, processing and integrations',
      description:
        'Статьи WayOfProcessing о процессинге Stripe, прогретых аккаунтах, интеграциях, payment routing и приёме международных платежей для бизнеса.',
      descriptionEn:
        'WayOfProcessing articles on Stripe processing, warmed accounts, integrations, payment routing and accepting international payments.',
    },
    privacy: {
      title: 'Политика конфиденциальности WayOfProcessing',
      titleEn: 'WayOfProcessing Privacy Policy',
      description:
        'Как WayOfProcessing собирает, использует и защищает персональные данные при использовании сайта и отправке заявок.',
      descriptionEn:
        'How WayOfProcessing collects, uses and protects personal data when you use our website and contact forms.',
    },
  },
}
